### PR TITLE
Assign the fork settings in the frontend twig template

### LINKED ISSUE #2163: THEME_URL is not set
## Type

- Critical bug

## Problem description

THEME_URL is not set because `$this->forkSettings` is `null` https://github.com/forkcms/forkcms/blob/master/src/Common/Core/Twig/BaseTwigTemplate.php#L142

## Steps to reproduce

Do this in your theme template: `{{ dump(THEME_URL) }}`

### PR DESCRIPTION
**Pull request by StijnVrolijk**
## Type

- Critical bugfix

## Issue

Fixes #2163

## Pull request description

During a cleanup of the twig templates this assignment was accidentally removed. This is needed to access stuff like the theme url, site title, ... in the frontend templates

### CODE REVIEW

File: src/Frontend/Core/Engine/TwigTemplate.php [hunk 1]
```diff
@@ -39,6 +39,7 @@ public function __construct(
         parent::__construct($environment, $parser, $locator);
 
         $container = Model::getContainer();
+        $this->forkSettings = $container->get('fork.settings');
```
Comment (carakas) [inline src/Frontend/Core/Engine/TwigTemplate.php]: Can you then also use $this->forkSettings at the other places where we get it from the container in this class?

**Comment by carakas** [comment]
@StijnVrolijk can you check my fixes?

**Comment by StijnVrolijk** [comment]
@carakas it's a bit dirty but if it works, it works! It's for tests anyway so yeah.. :shipit:
