### PR TITLE
Use POST request for deleting items

### LINKED ISSUE #2086: Use form to delete items
## Type
- Critical bug
- Enhancement

## Problem description
Deleting items should only be available trough POST requests. This is a CRSF security issue.

## Steps to reproduce
Try to delete blog post.

## Expected behavior / Proposed solutions
This should be a POST-request, but is a GET-request.

### PR DESCRIPTION
**Pull request by jonasdekeukelaere**
## Type
- Enhancement

## Resolves the following issues
fixes #2086 

## Pull request description
Use post request for deleting items instead of get request.

### CODE REVIEW

**Comment by jonasdekeukelaere** [comment]
3 more modules todo.

**Comment by jonasdekeukelaere** [comment]
@carakas all modules done

**Comment by carakas** [comment]
@jonasdekeukelaere so no longer [WIP] ?

**Comment by jonasdekeukelaere** [comment]
Yes. Oops forgot, removed it now.

**Comment by carakas** [comment]
@jonasdekeukelaere can you look at the merge conflicts ?

File: src/Backend/Modules/Blog/Actions/Delete.php [hunk 1]
```diff
@@ -10,8 +10,10 @@
  */
 
 use Backend\Core\Engine\Base\ActionDelete as BackendBaseActionDelete;
+use Backend\Core\Engine\Form;
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/Delete.php]: I think you don't need this usestatement

File: src/Backend/Modules/Blog/Actions/Delete.php [hunk 2]
```diff
@@ -28,17 +30,24 @@ class Delete extends BackendBaseActionDelete
 
     public function execute(): void
     {
+        $deleteForm = $this->createForm(BlogDeleteType::class);
+        $deleteForm->handleRequest($this->get('request'));
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/Delete.php]: you can do `$this->getRequest()`

File: src/Backend/Modules/Blog/Actions/Edit.php [hunk 3]
```diff
@@ -9,6 +9,8 @@
  * file that was distributed with this source code.
  */
 
+use Backend\Core\Engine\Form;
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/Edit.php]: I don't think you need this usestatement

File: src/Backend/Modules/Blog/Layout/Templates/EditCategory.html.twig [hunk 4]
```diff
@@ -63,28 +63,34 @@
...
-          </div>
-        </div>
-      {% endif %}
     </div>
   </div>
   {% endform %}
+
+  {% if showBlogDeleteCategory and allowBlogDeleteCategory %}
+    {{ form_start(deleteForm) }}
+    {{ form_row(deleteForm._token) }}
```
Comment (carakas) [inline src/Backend/Modules/Blog/Layout/Templates/EditCategory.html.twig]: is there a reason why you didn't use form_rest here and in the other templates?

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php [hunk 5]
```diff
@@ -31,33 +31,32 @@ public function execute(): void
...
+
+            // delete item
+            BackendBlogModel::deleteCategory($this->id);
+
+            // category was deleted, so redirect
+            $this->redirect(
+                BackendModel::createURLForAction('Categories') . '&report=deleted-category&var=' .
+                rawurlencode($this->record['title'])
+            );
+        } else {
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: you don't need this else since you will redirect.

Comment (carakas) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: we usually add a `return` below the redirect, the redirect will throw an exception but by adding the return it is more clear that the code stops there (if needed maybe also add that in other places)

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php [hunk 6]
```diff
@@ -31,33 +31,32 @@ public function execute(): void
...
+            $this->redirect(
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: here you wouldn't need the return since it will just be the last line

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php [hunk 7]
```diff
@@ -31,33 +31,32 @@ public function execute(): void
...
+                // delete category not allowed
+                BackendModel::createURLForAction('Categories') . '&error=delete-category-not-allowed&var=' .
+                rawurlencode($this->record['title'])
+            );
+        }
     }
 }
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: reviewed till here

File: src/Backend/Modules/Blog/Actions/Delete.php (hunk 2 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Actions/Delete.php]: Has been changed later, after the MR with that change has been merged.

File: src/Backend/Modules/Blog/Layout/Templates/EditCategory.html.twig (hunk 4 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Layout/Templates/EditCategory.html.twig]: I like it explicit, so it is clear what's there.

File: src/Backend/Modules/Blog/Actions/Delete.php (hunk 1 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Actions/Delete.php]: Oops, was probably from when I started with SpoonForm. Fixed b6cd3c3f1

File: src/Backend/Modules/Blog/Actions/Edit.php (hunk 3 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Actions/Edit.php]: Fixed b6cd3c3f1

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php (hunk 5 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: Fixed 217877c0f - I didn't add the return because I didn't see this anywhere else in the code base.

File: src/Backend/Modules/Blog/Layout/Templates/EditCategory.html.twig (hunk 4 above)
Comment (carakas) [inline src/Backend/Modules/Blog/Layout/Templates/EditCategory.html.twig]: ok

File: src/Backend/Modules/ContentBlocks/Actions/Delete.php [hunk 8]
```diff
@@ -31,19 +32,8 @@ public function execute(): void
...
-            $deleteFormData['id'],
-            Locale::workingLocale()
-        );
-
-        if ($contentBlock === null) {
-            $this->redirect(BackendModel::createURLForAction('Index', null, null, ['error' => 'non-existing']));
-
-            return;
-        }
+        /** @var ContentBlock $contentBlock */
```
Comment (carakas) [inline src/Backend/Modules/ContentBlocks/Actions/Delete.php]: this phpdoc is obsolete since you already get the typehint from the getContentBlock method

File: src/Backend/Modules/ContentBlocks/Actions/Delete.php [hunk 9]
```diff
@@ -31,19 +32,8 @@ public function execute(): void
...
+        $contentBlock = $this->getContentBlock((int) $deleteFormData['id']);
```
Comment (carakas) [inline src/Backend/Modules/ContentBlocks/Actions/Delete.php]: you don't need the cast here since we aren't using the strict mode so the method will autocast it to an int

File: src/Backend/Modules/ContentBlocks/Actions/Delete.php (hunk 8 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/ContentBlocks/Actions/Delete.php]: Should have been handled in https://github.com/forkcms/forkcms/pull/2096 - but fixed c0543e2e1

File: src/Backend/Modules/ContentBlocks/Actions/Delete.php (hunk 9 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/ContentBlocks/Actions/Delete.php]: Disagree, I think it's a good practice to send the right types. Looks a bit weird to send a string where an int is required.

File: src/Backend/Modules/Groups/Actions/Delete.php [hunk 10]
```diff
@@ -31,20 +31,19 @@ public function execute(): void
...
+            $this->redirect(BackendModel::createURLForAction('Index') . '&error=non-existing');
+        }
 
-            // get record
-            $this->record = BackendGroupsModel::get($this->id);
+        parent::execute();
 
-            // delete group
-            BackendGroupsModel::delete($this->id);
+        // get record
```
Comment (carakas) [inline src/Backend/Modules/Groups/Actions/Delete.php]: useless comment

File: src/Backend/Modules/Groups/Actions/Delete.php [hunk 11]
```diff
@@ -31,20 +31,19 @@ public function execute(): void
...
+        $this->record = BackendGroupsModel::get($this->id);
 
-            // item was deleted, so redirect
-            $this->redirect(BackendModel::createURLForAction('Index') . '&report=deleted&var=' . rawurlencode($this->record['name']));
-        } else {
-            // no item found, redirect to the overview with an error
-            $this->redirect(BackendModel::createURLForAction('Index') . '&error=non-existing');
-        }
+        // delete group
```
Comment (carakas) [inline src/Backend/Modules/Groups/Actions/Delete.php]: likewise

File: src/Backend/Modules/Groups/Actions/Delete.php [hunk 12]
```diff
@@ -31,20 +31,19 @@ public function execute(): void
         $this->id = $deleteFormData['id'];
 
         // group exists and id is not null?
```
Comment (carakas) [inline src/Backend/Modules/Groups/Actions/Delete.php]: I would remove the comment since it is no longer correct and is just saying what the code said

File: src/Backend/Modules/Location/Js/Location.js [hunk 13]
```diff
@@ -11,7 +11,7 @@ jsBackend.location =
     init: function()
     {
         // only show a map when there are options and markers given
-        if(typeof markers != 'undefined' && typeof mapOptions != 'undefined')
+        if($('#map').length > 0 && typeof markers != 'undefined' && typeof mapOptions != 'undefined')
```
Comment (carakas) [inline src/Backend/Modules/Location/Js/Location.js]: maybe checking on the id `map` is too generic

File: src/Backend/Modules/MediaGalleries/Actions/MediaGalleryDelete.php [hunk 14]
```diff
@@ -36,13 +44,11 @@ public function execute(): void
         );
     }
 
-    private function getMediaGallery(): MediaGallery
+    private function getMediaGallery(string $id): MediaGallery
```
Comment (carakas) [inline src/Backend/Modules/MediaGalleries/Actions/MediaGalleryDelete.php]: I think the mediaGallery works with uuid not string, @jeroendesloovere ?

File: src/Backend/Modules/MediaLibrary/Actions/MediaItemDelete.php [hunk 15]
```diff
@@ -29,13 +37,11 @@ public function execute(): void
         );
     }
 
-    private function getMediaItem(): MediaItem
+    private function getMediaItem(string $id): MediaItem
```
Comment (carakas) [inline src/Backend/Modules/MediaLibrary/Actions/MediaItemDelete.php]: idem

File: src/Backend/Modules/Profiles/Actions/Delete.php [hunk 16]
```diff
@@ -32,37 +32,37 @@ public function execute(): void
...
-                    ) . '&highlight=row-' . $profile['id']
-                );
-            }
+            // redirect
+            $this->redirect(
+                BackendModel::createURLForAction('Index') . '&report=profile-undeleted&var=' . rawurlencode(
+                    $profile['email']
+                ) . '&highlight=row-' . $profile['id']
+            );
         } else {
```
Comment (carakas) [inline src/Backend/Modules/Profiles/Actions/Delete.php]: useless else since you redirect, but add a return to make it clear that it is the end

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php [hunk 17]
```diff
@@ -51,12 +51,12 @@ public function execute(): void
                 BackendModel::createURLForAction('Categories') . '&report=deleted-category&var=' .
                 rawurlencode($this->record['title'])
             );
```
Comment (carakas) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: still missing a return here, below a this->redirect if it is not the last line of the method should be a return, in the old code that wasn't present becaus it used the if else structure thereby making it the "last" line of executed code

File: src/Backend/Modules/Faq/Form/FaqDeleteType.php [hunk 18]
```diff
@@ -0,0 +1,18 @@
+<?php
+
+namespace Backend\Modules\Faq\Form;
+
+use Backend\Core\Engine\Model;
+use Symfony\Component\Form\AbstractType;
+use Symfony\Component\Form\Extension\Core\Type\HiddenType;
+use Symfony\Component\Form\FormBuilderInterface;
+
+final class FaqDeleteType extends AbstractType
```
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Form/FaqDeleteType.php]: And that already fails with Blog, because there is an extra category id

File: src/Backend/Modules/Location/Js/Location.js (hunk 13 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Location/Js/Location.js]: Maybe, but that is wat is used to create the map => https://github.com/jonasdekeukelaere/forkcms/blob/fe871255770df0a93cb4cdd54f2e8d264c08e46c/src/Backend/Modules/Location/Js/Location.js#L272

File: src/Backend/Modules/MediaGalleries/Actions/MediaGalleryDelete.php (hunk 14 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/MediaGalleries/Actions/MediaGalleryDelete.php]: that's why it is a string ;)

File: src/Backend/Modules/Faq/Form/FaqDeleteType.php (hunk 18 above)
Comment (carakas) [inline src/Backend/Modules/Faq/Form/FaqDeleteType.php]: You can always extend the form for the exceptions, or even add an extra field in the controller.
I don't think that one exception is enough to justify this overhead

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php (hunk 5 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: Return added in 69c1c73

File: src/Backend/Modules/Groups/Actions/Delete.php (hunk 12 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Groups/Actions/Delete.php]: Fixed 2bf3bdb70

File: src/Backend/Modules/Groups/Actions/Delete.php (hunk 10 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Groups/Actions/Delete.php]: Fixed f3cadfe

File: src/Backend/Modules/Groups/Actions/Delete.php (hunk 11 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Groups/Actions/Delete.php]: Fixed f3cadfe

File: src/Backend/Modules/Profiles/Actions/Delete.php (hunk 16 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Profiles/Actions/Delete.php]: Fixed 842a2c6

File: src/Backend/Modules/Blog/Actions/DeleteCategory.php (hunk 17 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Blog/Actions/DeleteCategory.php]: Fixed 842a2c6

File: src/Backend/Modules/MediaGalleries/Actions/MediaGalleryDelete.php (hunk 14 above)
Comment (carakas) [inline src/Backend/Modules/MediaGalleries/Actions/MediaGalleryDelete.php]: I thought it used the class uuid but is is indeed the string version

File: src/Backend/Modules/Faq/Actions/DeleteCategory.php [hunk 19]
```diff
@@ -24,37 +24,48 @@ public function execute(): void
...
         }
+
+        $this->record = (array) BackendFaqModel::getCategory($this->id);
+
+        if (!BackendFaqModel::deleteCategoryAllowed($this->id)) {
+            $this->redirect(BackendModel::createURLForAction(
+                'Categories',
+                null,
+                null,
+                ['error' => 'delete-category-not-allowed', 'var' => $this->record['title']]
```
Comment (carakas) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: will this handle the `rawurlencode` ?

Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: yes, http_query_build doet url-encoding https://github.com/forkcms/forkcms/blob/5.0.0-dev/src/Backend/Core/Engine/Model.php#L99

Comment (carakas) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: that also is the reason your tests are failing, spaces are now translated to `+` instead of `%20`

Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: Hmm, haven't looked at that yet, still working on the general delete form type. Do I change the tests to +? Or do I change the http_query_build enc_type to PHP_QUERY_RFC3986 so spaces are translated back to %20?

Comment (carakas) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: @forkcms/core-contributors what do you think?

Comment (carakas) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: I think that %20 has the benefit that you always know it should be a space and that no information is lost, but I'd like to hear the input from the others as well.

Comment (tijsverkoyen) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: %20 or + doesn't make a difference, it is just another way of encoding it

File: src/Backend/Modules/Faq/Form/FaqDeleteType.php (hunk 18 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Form/FaqDeleteType.php]: Fixed in in separate commits, 06eb6ccbf

File: src/Backend/Modules/Faq/Actions/Edit.php [hunk 20]
```diff
@@ -152,7 +151,11 @@ private function validateForm(): void
 
     private function loadDeleteForm(): void
     {
-        $deleteForm = $this->createForm(FaqDeleteType::class, ['id' => $this->record['id']]);
+        $deleteForm = $this->createForm(
+            DeleteType::class,
```
Comment (carakas) [inline src/Backend/Modules/Faq/Actions/Edit.php]: the use statement is missing

Comment (carakas) [inline src/Backend/Modules/Faq/Actions/Edit.php]: @jonasdekeukelaere it is hidden as outdated but I think it is still in there

Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Actions/Edit.php]: it is there, because I tested it -> https://github.com/jonasdekeukelaere/forkcms/blob/90a8e1a9a0cd8eec0ad9f543edaac4d8cd8c0aa0/src/Backend/Modules/Faq/Actions/Edit.php#L17

Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Actions/Edit.php]: because it has been added in the previous commit (for faq feedback) ;)

File: src/Backend/Modules/Faq/Actions/DeleteCategory.php (hunk 19 above)
Comment (jonasdekeukelaere) [inline src/Backend/Modules/Faq/Actions/DeleteCategory.php]: changed the tests 90a8e1a

**Comment by jonasdekeukelaere** [comment]
@carakas I think all feedback has been handled
