### PR TITLE
Fix the HTTPS detection when getting the configuration during install

### LINKED ISSUE #2614: Detect install over HTTPS and write it ot parameter.yml
## Type

- Non critical bug

## Problem description

When installing ForkCMS into an HTTPS server, `parameter.yml` contains ``http` in `site.protocol`.

## Steps to reproduce

Install ForkCMS into an HTTPS server.

## Expected behavior / Proposed solutions

`parameter.yml` should contain``https` in `site.protocol`.

### PR DESCRIPTION
**Pull request by StijnVrolijk**
## Type
- Non critical bugfix

## Resolves the following issues
fixes #2614 

## Pull request description
Use the `HTTPS` server variable's existence instead of checking the `SERVER_PROTOCOL` variable.
See http://php.net/manual/en/reserved.variables.server.php

### CODE REVIEW

File: src/ForkCMS/Bundle/InstallerBundle/Service/ForkInstaller.php [hunk 1]
```diff
@@ -307,9 +307,7 @@ protected function getConfigurationVariables(InstallationData $data): array
             '<database-user>' => addslashes($data->getDatabaseUsername()),
             '<database-password>' => addslashes($data->getDatabasePassword()),
             '<database-port>' => $data->getDatabasePort(),
-            '<site-protocol>' => isset($_SERVER['SERVER_PROTOCOL']) ?
-                (mb_strpos(mb_strtolower($_SERVER['SERVER_PROTOCOL']), 'https') === false ? 'http' : 'https') :
-                'http',
+            '<site-protocol>' => isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) ? 'https' : 'http',
```
Comment (carakas) [inline src/ForkCMS/Bundle/InstallerBundle/Service/ForkInstaller.php]: https can also contain the text off
