### PR TITLE
Tags: Remove empty elements from array

### LINKED ISSUE #1103: Blog/tags array_fill exception
Just did a fresh git clone of Fork CMS and installed it. I went to the blog module and chose to edit one of the two installed example articles. When I save it, I get the following exception:

	ContextErrorException: Warning: array_fill(): Number of elements must be positive in /home/vagrant/apps/default/fork-cms/forktest/src/Backend/Modules/Tags/Engine/Model.php line 297

	in /home/vagrant/apps/default/fork-cms/forktest/src/Backend/Modules/Tags/Engine/Model.php line 297
	at ErrorHandler->handle('2', 'array_fill(): Number of elements must be positive', '/home/vagrant/apps/default/fork-cms/forktest/src/Backend/Modules/Tags/Engine/Model.php', '297', array('otherId' => '1', 'tags' => array(), 'module' => 'Blog', 'language' => 'en', 'db' => object(SpoonDatabase), 'currentTags' => array(), 'key' => '0', 'tag' => ''))
	at array_fill('0', '0', '?') in /home/vagrant/apps/default/fork-cms/forktest/src/Backend/Modules/Tags/Engine/Model.php line 297
	at Model::saveTags('1', '', 'Blog') in /home/vagrant/apps/default/fork-cms/forktest/src/Backend/Modules/Blog/Actions/Edit.php line 448

Same thing happens when I create a new blog article without tags. Seems like the error happens at:

    $placeholders = array_fill(0, count($tags), '?');

On line 282 there's a check if the tags array is not empty (`if (!empty($tags))`). The installed example articles don't have tags, but I saw in the debugger that the tags array actually isn't empty: `$tags[0] = ""`. Because of this, the array is not empty and the code gets executed while it should not....

### PR DESCRIPTION
**Pull request by megasnort**
Problem was indeed the empty element which caused the empty-function to return false. Closes #1103

### CODE REVIEW

File: src/Backend/Modules/Tags/Engine/Model.php [hunk 1]
```diff
@@ -258,6 +258,9 @@ public static function saveTags($otherId, $tags, $module, $language = null)
         // make sure the list of tags is unique
         $tags = array_unique($tags);
 
+        // remove empty elements
+        $tags = array_filter($tags);
```
Comment (WouterSioen) [inline src/Backend/Modules/Tags/Engine/Model.php]: can't you do this in one line? `$tags = array_filter(array_unique($tags));`

**Comment by megasnort** [comment]
Made it a bit shorter.
