### PR TITLE
1978 fix locale analyse

### LINKED ISSUE #1978: Locale analyse doesn't work correctly
## Type

- Non critical bug

## Problem description

/locale/analyse -> i get the message : 'No missing translations were found.' but there are missing translation , so i guess something went wrong.

## Steps to reproduce

Go to /locale/analyse

### PR DESCRIPTION
**Pull request by carakas**
## Type

- Non critical bugfix

## Resolves the following issues

fixes #1978 

## Pull request description

This will fix the long broken analysis of the translations in fork

### CODE REVIEW

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php [hunk 1]
```diff
@@ -22,7 +24,47 @@ public function __construct(string $application, string $modulesPath, array $ins
...
+     */
+    private function getInBetweenStrings(string $start, string $end, string $str)
+    {
+        $matches = [];
+        preg_match_all("@$start([a-zA-Z0-9_]*)$end@", $str, $matches);
+
+        return isset($matches[1]) ? current($matches[1]) : '';
+    }
+
+    private function findModuleFiles(): array
```
Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: Wouldn't it be more logical to loop all modules and fetch each's files? I know that ignores modules that aren't installed but it seems to make more sense

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php [hunk 2]
```diff
@@ -47,6 +49,76 @@ private function getInBetweenStrings(string $start, string $end, string $str)
...
+            '"\.locale\.(act|err|lbl|msg)\(\'(\w+?)\'(?:, ?\'(\w+?)\')?\)"',
+            '"\.locale\.get\(\'(\w+?)\', ?\'(\w+?)\'(?:, ?\'(\w+?)\')?\)"',
+        ];
+        foreach ($patterns as $pattern) {
+            $matches = [];
+            preg_match_all($pattern, $fileContent, $matches);
+            $locale[] = $this->getLocaleArrayFromRegexMatches($this->getDefaultModule($moduleName), $matches);
+        }
+
+        if (count($locale) === 0) {
```
Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: I prefer using `empty` as it increases readability and is actually better performance wise 

https://stackoverflow.com/questions/2216110/checking-for-empty-arrays-count-vs-empty

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php [hunk 3]
```diff
@@ -47,6 +49,76 @@ private function getInBetweenStrings(string $start, string $end, string $str)
...
+        }
+    }
+
+    private function findLocaleInModuleFiles(string $moduleName, array $module): array
+    {
+        $locale = [];
+        foreach ($module as $filename => $file) {
+            $fileLocale = $this->findLocaleInFile($moduleName, $filename, $file);
+
+
```
Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: Obsolete whitespace

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php [hunk 4]
```diff
@@ -70,7 +70,6 @@ private function findLocaleInModuleFiles(string $moduleName, array $module): arr
         foreach ($module as $filename => $file) {
             $fileLocale = $this->findLocaleInFile($moduleName, $filename, $file);
 
-
```
Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: 👍

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php [hunk 5]
```diff
@@ -25,11 +25,47 @@ public function __construct(string $application, string $modulesPath, array $ins
...
+
+                            if (array_key_exists($nonExistingKey, $nonExisting)) {
+                                $usedInFiles = unserialize($nonExisting[$nonExistingKey]['used_in']);
+                                $usedInFiles[] = $file['file'];
+                                $nonExisting[$nonExistingKey]['used_in'] = serialize($usedInFiles);
+
+                                continue;
+                            }
+
+                            $nonExisting[$nonExistingKey] = [
```
Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: Would it be an idea to create a value object (of some sort) to hold this data? Seems a bit more robust than a simple array. Not saying you have to do it, I just think it may be a good idea

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php [hunk 6]
```diff
@@ -162,4 +198,51 @@ private function getDefaultModule(string $currentModuleName): string
...
+        foreach ($array1 as $key => $value) {
+            if (!array_key_exists($key, $array2) || !is_array($value)) {
+                if (!in_array($value, $array2, true)) {
+                    $outputDiff[$key] = $value;
+                }
+
+                continue;
+            }
+
+            if (is_array($value)) {
```
Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]:
```
if (!is_array($value)) {
  continue;
}
```

for improved readability :)

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php (hunk 5 above)
Comment (carakas) [reply src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: As discussed in person: I think it is overkill and not very useful since the array is also the source of a datagrid

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php (hunk 1 above)
Comment (carakas) [reply src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: I think it would make the code more complex

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php (hunk 6 above)
Comment (carakas) [reply src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: fixed in 3bed9c3b4

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php (hunk 2 above)
Comment (carakas) [reply src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: fixed in 13b1f8df6

Comment (carakas) [reply src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: fixed in 13b1f8df6

File: src/Backend/Modules/Locale/Engine/LocaleAnalyser.php (hunk 6 above)
Comment (carakas) [reply src/Backend/Modules/Locale/Engine/LocaleAnalyser.php]: fixed in 3bed9c3b4
