### PR TITLE
Partly fixed deprecations of Twig #2777

### LINKED ISSUE #2777: Twig deprecations
## Type

> remove the types that don't apply
> If you discover any security related issues, please email core@fork-cms.com instead of using the issue tracker.

- Enhancement

## Problem description

Since twig 2.7 some classes we extend are deprecated. We need to change them.
## Steps to reproduce

Look in the debug bar for the deprecations

## Expected behavior / Proposed solutions
Don't use deprecated twig classes

### PR DESCRIPTION
**Pull request by aalwash**
## Type
- Enhancement

## Resolves the following issues
Partly fixes #2777

## Pull request description
I'm not done with all deprecations, some of them are a bit harder, like
`User Deprecated: The "Symfony\Bridge\Twig\Extension\FormExtension" class implements "Twig\Extension\InitRuntimeInterface" that is deprecated since Twig 2.7, to be removed in 3.0.`

### CODE REVIEW

File: src/Common/Core/Twig/Extensions/TwigFilters.php [hunk 1]
```diff
@@ -5,83 +5,84 @@
...
 {
     /**
      * //http://twig.sensiolabs.org/doc/advanced.html#id2
      * returns a collection of Twig SimpleFilters
      *
-     * @param Twig_Environment $twig
+     * @param Environment $twig
      * @param string $app
      */
-    public static function addFilters(Twig_Environment $twig, string $app): void
```
Comment (carakas) [inline src/Common/Core/Twig/Extensions/TwigFilters.php]: is this change backwards compatible?

Comment (aalwash) [reply src/Common/Core/Twig/Extensions/TwigFilters.php]: It's definitely not backward compatible

But I've checked the usage of TwigFilters, that only happens in the Frontend/Backend Engine
And both are rewritten to pass the new Twig\Environment class

Do extensions call the Frontend/Backend Engine them self?

Comment (aalwash) [reply src/Common/Core/Twig/Extensions/TwigFilters.php]: Btw, I forgot to mention that I've done some random filter tests after the Twig changes and it worked for me so far
