### PR TITLE
2493 add missing toggle navigation label in the frontend

### LINKED ISSUE #2493: Strange and unworking label {$lblToggleNavigation} in src\Frontend\Themes\Fork\Core\Layout\Templates\Base.html.twig
## Type
Strange and unworking label {$lblToggleNavigation} in src\Frontend\Themes\Fork\Core\Layout\Templates\Base.html.twig on line 15 in class="sr-only"

- Non critical bug

## Steps to reproduce

```          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">{$lblToggleNavigation}</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/{{ LANGUAGE }}">{{ siteTitle }}</a>
          </div>
```
## Expected behavior / Proposed solutions

Screenshot from https://demo.fork-cms.com/en
https://yadi.sk/i/bgevTWJw3SrWeA

### PR DESCRIPTION
**Pull request by carakas**
## Type

- Non critical bugfix

## Resolves the following issues
fixes #2493

## Pull request description

Show the correct tekst to screenreaders in the frontend navigation toggle

### CODE REVIEW

File: src/Frontend/Core/Js/frontend.js [hunk 1]
```diff
@@ -69,11 +69,25 @@ jsFrontend.controls = {
...
+    var $navToggle = $('.navbar-toggle')
+
+    if ($navToggle.length === 0) {
+      return
+    }
+
+    $navToggle.on('click', function() {
+      var $button = $(this)
+      $button.find('[data-role=label]').text(jsFrontend.locale.lbl($button.hasClass('collapsed') ? 'CloseNavigation' : 'OpenNavigation'))
+    }).find('[data-role=label]').text(jsFrontend.locale.lbl($navToggle.hasClass('collapsed') ? 'CloseNavigation' : 'OpenNavigation'))
```
Comment (WouterSioen) [inline src/Frontend/Core/Js/frontend.js]: Don't we do semicolons anymore?

Comment (carakas) [reply src/Frontend/Core/Js/frontend.js]: not, apparently frontenders have decided that they don't like them, probably some anti php-league :p 
https://standardjs.com/#standardjs--the-rules
