### PR TITLE
Locale fixes

### LINKED ISSUE #2186: Translation edit in index is broken
## Type

- Critical bug

## Problem description

Edit of translation in index is broken, got an ajax error.

## Steps to reproduce

http://demo.forkcms.com/private/en/locale/index?form=filter&form_token=93df333ed5f53a4f9475c2dcb5997f71&application=&module=&type%5B%5D=lbl&language%5B%5D=fr&name=e&value=&search=
Try to change the first translation and the error will appear

`{"code":500,"data":null,"message":"Module not allowed."}`

### PR DESCRIPTION
**Pull request by StijnVrolijk**
## Type

- Critical bugfix

## Resolves the following issues

fixes #2186

## Pull request description

The `type` field of the locale is no longer an ENUM in the database so `getEnumValues` doesn't work anymore. I've decided to replace it with a query that basically does the same but ideally it should be rewritten as a ValueObject that's used throughout Fork.

In addition to that, there was an incorrect return type in `getByName` which caused the id to always be `1`

### CODE REVIEW

File: src/Backend/Modules/Locale/Ajax/SaveTranslation.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ public function execute(): void
         }
         $name = $this->getRequest()->request->get('name', '');
         $type = $this->getRequest()->request->get('type');
-        if (!in_array($type, BackendModel::get('database')->getEnumValues('locale', 'type'))) {
```
Comment (carakas) [inline src/Backend/Modules/Locale/Ajax/SaveTranslation.php]: is this the only usecase left of getEnumValues?

Comment (StijnVrolijk) [inline src/Backend/Modules/Locale/Ajax/SaveTranslation.php]: It is

**Comment by pradysharma** [comment]
[Rajasthan High Court LDC Result 2017](url=http://seatallotment.in/rajasthan-high-court-ldc-result/) 
[Allahabad High Court LDC Result 2017 ](url=http://seatallotment.in/allahabad-high-court-group-c-result-cut-off-date-merit-list/)

**Comment by pradysharma** [comment]
[Allahabad High Court Group C Result 2017](http://seatallotment.in/allahabad-high-court-group-c-result-cut-off-date-merit-list/)

**Comment by pradysharma** [comment]
[Rajasthan High Court LDC Result 2017 ](http://seatallotment.in/rajasthan-high-court-ldc-result/)
[TS TET Result 2017 ](http://seatallotment.in/ts-tet-results/)

**Comment by carakas** [comment]
Removed spam comment, wow, spam, already made it's way to github…
