### PR TITLE
Just return if getting the navigation html goes wrong

### LINKED ISSUE #1575: getnavigation crashes when having only a home page AND setting parent to 1
Exception is thrown which states that the parent doesn't exist.
Possible solution: return empty navigationlist.

### PR DESCRIPTION
**Pull request by carakas**
This fixes #1575

### CODE REVIEW

File: src/Frontend/Core/Engine/TemplateModifiers.php [hunk 1]
```diff
@@ -87,7 +87,12 @@ public static function getNavigation(
         }
 
         // get HTML
-        $return = (string) Navigation::getNavigationHtml($type, $parentId, $depth, $excludeIds, $template);
+        try {
+            $return = (string) Navigation::getNavigationHTML($type, $parentId, $depth, $excludeIds, $template);
+        } catch (Exception $e) {
+            // if something goes wrong just return as fallback
+            return;
```
Comment (WouterSioen) [inline src/Frontend/Core/Engine/TemplateModifiers.php]: the phpdoc states `return string`. I would return an empty string here to keep consistency

Comment (carakas) [inline src/Frontend/Core/Engine/TemplateModifiers.php]: fixed in 5a38785
