### PR TITLE
Fixes #1174, use date_format_short from settings to format $form->addDate.

### LINKED ISSUE #1174: Frontend input date field reformats date incorrect
I created a custom form on the frontend with the following code:
```php
$date = new \DateTime('today');
$form->addDate('start_date', $date->getTimestamp());
```

On the frontend in the code the date is written as `02/05/2015` but jQuery changes it to `05/02/2015` which is wrong because today is `02/05/2015`. I can't find the problem, it happens since I updated from 3.8.7 to 3.9.1.

### PR DESCRIPTION
**Pull request by ikoene**
Solves #1174

### CODE REVIEW

File: src/Frontend/Core/Engine/Form.php [hunk 1]
```diff
@@ -161,8 +161,8 @@ public function addDate(
             throw new Exception('A date field with type "range" should have 2 valid date-parameters.');
         }
 
-        // @later	get preferred mask & first day
-        $mask = 'd/m/Y';
+        // set mask and firstday
+        $mask = Model::getContainer()->get('fork.settings')->get('Core', 'date_format_short');
```
Comment (WouterSioen) [inline src/Frontend/Core/Engine/Form.php]: You can just use `Model::get('fork.settings')->get('Core', 'date_format_short')`

Tip: if you commit this, you can use `git commit --amend` to add it to this commit. You'll need to force push though :)

**Comment by WouterSioen** [comment]
:+1:

File: src/Frontend/Core/Engine/Form.php (hunk 1 above)
Comment (ikoene) [inline src/Frontend/Core/Engine/Form.php]: Fixed.
