### PR TITLE
Unset the linked contentblock when using data for new locale

### LINKED ISSUE #2248: Pages copy action sets content blocks of from language archived
## Type

- Critical bug

## Problem description

When you want to make a copy from the NL website to the FR website, the content blocks of NL get archived.

## Steps to reproduce

`/pages/copy?from=nl&to=fr`

### PR DESCRIPTION
**Pull request by bjorvack**
## Type

- Critical bugfix

## Resolves the following issues
fixes #2248

## Pull request description

Unsets the related contentblock when copying data over.

### CODE REVIEW

File: src/Backend/Modules/ContentBlocks/Domain/ContentBlock/Command/CopyContentBlocksToOtherLocaleHandler.php [hunk 1]
```diff
@@ -30,10 +30,11 @@ function (ContentBlock $contentBlock) use ($copyContentBlocksToOtherLocale, &$id
                 $dataTransferObject = $contentBlock->getDataTransferObject();
 
                 // Overwrite some variables
-                $dataTransferObject->id = $id++;
-                $dataTransferObject->extraId = $copyContentBlocksToOtherLocale->extraIdMap[$contentBlock->getExtraId()];
-                $dataTransferObject->revisionId = null;
-                $dataTransferObject->locale = $copyContentBlocksToOtherLocale->toLocale;
+                $dataTransferObject->forOtherLocale(
+                    $id ++,
```
Comment (carakas) [inline src/Backend/Modules/ContentBlocks/Domain/ContentBlock/Command/CopyContentBlocksToOtherLocaleHandler.php]: there shouldn't be a space

Comment (bjorvack) [reply src/Backend/Modules/ContentBlocks/Domain/ContentBlock/Command/CopyContentBlocksToOtherLocaleHandler.php]: fixed b43c63685
