### PR TITLE
Make sure our key length isn't over 1000 bytes. - fixes #1524

### LINKED ISSUE #1524: Installer step 6 failed (Uncaught PHP Exception PDOException)
### Uncaught PHP Exception PDOException

Fork CMS 4.0.2
PHP 5.6.15
MySQL 5.7.9
Apache 2.4.17
On WampServer

> request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes" at D:\wamp\www\cms\fork\vendor\spoon\library\spoon\database\database.php line 288 {"exception":"[object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes at D:\\wamp\\www\\cms\\fork\\vendor\\spoon\\library\\spoon\\database\\database.php:288)"} []

### PR DESCRIPTION
**Pull request by WouterSioen**
utf8mb4 multiplies the used bytes with 4

### CODE REVIEW

File: src/Backend/Core/Installer/Data/install.sql [hunk 1]
```diff
@@ -11,7 +11,7 @@ CREATE TABLE IF NOT EXISTS `meta` (
   `custom` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'used for custom meta-information',
   `data` text COMMENT 'used for extra meta-information',
   PRIMARY KEY (`id`),
-  KEY `idx_url` (`url`)
+  KEY `idx_url` (`url`(249))
```
Comment (jessedobbelaere) [inline src/Backend/Core/Installer/Data/install.sql]: 👍 
Actually, can be 250 maybe? 250 * 4 = 1000 so fits exactly the available 1000 bytes

Comment (WouterSioen) [inline src/Backend/Core/Installer/Data/install.sql]: I've read on the big internet that 249 was more safe, but not sure if this is right, since I can't reproduce this issue (probably because of other limits in mariadb).

Comment (jessedobbelaere) [inline src/Backend/Core/Installer/Data/install.sql]: Ah ok 249 is fine too then 👍 merge away
