### PR TITLE
Fix php 7 compatibility problems

### LINKED ISSUE #1325: possible php7 and future incompatiblities
Tested with https://github.com/sstalle/php7cc

```
$ php7cc src/ --except=src/Backend/Core/Js/ckeditor/ src/Backend/Core/Js/ckfinder/

File: /Users/woutersioen/Sites/forkcms/forkcms/src/Backend/Core/Engine/Base/Object.php
> Line 26: Name "object" that is reserved for future use (does not cause an error in PHP 7) used as a class, interface or trait name
    class Object extends \KernelLoader
    {
    }


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Backend/Core/Engine/Cronjob.php
> Line 14: Name "object" that is reserved for future use (does not cause an error in PHP 7) used as a use statement alias
    Backend\Core\Engine\Base\Object


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Backend/Core/Installer/ModuleInstaller.php
> Line 740: Function argument(s) returned by "func_get_arg" might have been modified
    func_get_arg($i + 2);


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Backend/Modules/Mailmotor/Actions/ImportGroups.php
> Line 74: Nested by-reference foreach loop, make sure there is no iteration over the same array
    foreach ($customFields as &$field) {
    }


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Backend/Modules/Mailmotor/Engine/CMHelper.php
> Line 323: Possible adding to array on the last iteration of a by-reference foreach loop
    $records[$record] = $record;
> Line 630: Possible adding to array on the last iteration of a by-reference foreach loop
    $records[$record] = $record;


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Frontend/Core/Engine/Base/Object.php
> Line 22: Name "object" that is reserved for future use (does not cause an error in PHP 7) used as a class, interface or trait name
    class Object extends \KernelLoader
    {
    }


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Frontend/Core/Engine/Page.php
> Line 484: Nested by-reference foreach loop, make sure there is no iteration over the same array
    foreach ($blocks as $index => &$block) {
    }


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Frontend/Modules/FormBuilder/Widgets/Form.php
> Line 339: Nested by-reference foreach loop, make sure there is no iteration over the same array
    foreach ($field['html'] as &$item) {
    }


File: /Users/woutersioen/Sites/forkcms/forkcms/src/Frontend/Modules/Pages/Widgets/PreviousNextNavigation.php
> Line 77: Possible internal array pointer access/modification in a by-value foreach loop
    next($pagesNext);

Checked 636 files in 108.744 seconds
```

### PR DESCRIPTION
**Pull request by carakas**
## Type

- Critical Bugfix

## Resolves the following issues

closes #1325 

## Pull request description

Solves the last remaining php 7 incompatibility by removing the Object classes

### CODE REVIEW

File: UPGRADE_5.0.md [hunk 1]
```diff
@@ -280,3 +280,17 @@ Backend\Core\Engine\Base\AjaxAction and Frontend\Core\Engine\Base\AjaxAction no
 | self::ERROR           | Response::HTTP_INTERNAL_SERVER_ERROR |
 
 The response class has many more constants like this for all the other status codes
+
+## BackendNavigation
+
+`Backend\Core\Engine\Navigation` also known as the service `navigation` when you are in the backend was stripped of some functions that where available because it extended a base class. 
+This is no longer the case.
+The dropped methods are:
+* getAction
```
Comment (tijsverkoyen) [inline UPGRADE_5.0.md]: Wouldn't it be nice if you explain what a good alternative would be. As it may occur that people rely on these methods.

File: UPGRADE_5.0.md [hunk 2]
```diff
@@ -294,3 +294,17 @@ The dropped methods are:
 * redirect
 * redirectToErrorPage
 * getConfig
+
+## Backend Header
+
+`Backend\Core\Engine\Header` also known as the service `header` when you are in the backend was stripped of some functions that where available because it extended a base class. 
+This is no longer the case.
+The dropped methods are:
+* getAction
```
Comment (tijsverkoyen) [inline UPGRADE_5.0.md]: Shouldn't it be nice if you give them pointers to the correct alternatives.

File: src/Backend/Core/Engine/Base/Config.php [hunk 3]
```diff
@@ -127,6 +122,22 @@ public function isActionAvailable(string $action): bool
         return false;
     }
 
+    public function isActionAvailableForActionType(string $action, string $actionType): bool
+    {
+        // If this action is disabled for this type, continue on to the next type
```
Comment (tijsverkoyen) [inline src/Backend/Core/Engine/Base/Config.php]: Weird comment. It doesn't continue at all. It lets the caller know the given action is not available.

File: src/Backend/Core/Engine/Base/Config.php [hunk 4]
```diff
@@ -127,6 +122,22 @@ public function isActionAvailable(string $action): bool
...
+        if ($this->isActionDisabled($actionType, $action)) {
+            return false;
+        }
+
+        // If the action file is missing, continue on to the next type
```
Comment (tijsverkoyen) [inline src/Backend/Core/Engine/Base/Config.php]: Idem

File: src/Backend/Core/Engine/Base/Config.php [hunk 5]
```diff
@@ -136,20 +147,36 @@ private function isActionDisabled(string $actionType, string $action): bool
                 return in_array($action, $this->disabledAJAXActions, true);
         }
 
-        throw new \Exception($actionType . ' is not a valid action type');
+        throw new InvalidArgumentException($actionType . ' is not a valid action type');
```
Comment (tijsverkoyen) [inline src/Backend/Core/Engine/Base/Config.php]: I know this was in the original code. But looks like throwing an exception here is not the scope of this method

File: src/Backend/Core/Engine/Base/Config.php [hunk 6]
```diff
@@ -179,4 +180,31 @@ private function buildActionClass(string $actionType, string $action): string
...
+     * Other configurations will be stored in it also.
+     *
+     * @param KernelInterface $kernel
+     * @param string $module
+     *
+     * @return self
+     */
+    public static function forModule(KernelInterface $kernel, string $module): self
+    {
+        // check if we can load the config file
```
Comment (tijsverkoyen) [inline src/Backend/Core/Engine/Base/Config.php]: comment makes no sense

File: UPGRADE_5.0.md [hunk 7]
```diff
@@ -319,5 +319,11 @@ These changes are mostly internal but it might be good to know in case you did s
...
 | `Object::redirect`            | `\Backend\Core\Engine\Url::redirect`            |
 | `Object::redirectToErrorPage` | `\Backend\Core\Engine\Url::redirectToErrorPage` |
+| `Object::getAction`           | `\Backend\Core\Engine\Url::getAction`           |
+| `Object::getModule`           | `\Backend\Core\Engine\Url::getModule`           |
 
  The `\Backend\Core\Engine\Base\Action` class has a redirect helper method that uses the `\Backend\Core\Engine\Url` implementation so you don't need to change anything in your code for this
+
+You can no longer access module and action as a protected property on the action or ajax class but you need to use the getters as they are now only stored in the url service
+
+We did add helper getters so you can keep doing `$this->getAction()` and `$this->getModule()` as they will get the correct values from the url service
```
Comment (tijsverkoyen) [inline UPGRADE_5.0.md]: Is this usefull? In my opinion this means the url-service is injected. So they can use the service directly. The helper-methods just add more magic ✨

File: src/Backend/Core/Engine/Base/Action.php [hunk 8]
```diff
@@ -76,14 +77,20 @@ public function __construct(KernelInterface $kernel)
...
 
-        // store the current module and action (we grab them from the URL)
-        $this->setModule($this->URL->getModule());
-        $this->setAction($this->URL->getAction());
-
         // populate the parameter array
         $this->parameters = $this->get('request')->query->all();
     }
 
+    public function getModule(): string
```
Comment (tijsverkoyen) [inline src/Backend/Core/Engine/Base/Action.php]: See above

File: src/Frontend/Core/Engine/Base/Block.php [hunk 9]
```diff
@@ -85,6 +87,20 @@ class Block extends Object
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Base/Block.php]: Shouldn't this be `protected $url`, in the past we used uppercase for abbreviation, but this conflicts with using uppercase for constants.

File: src/Frontend/Core/Engine/Base/Widget.php [hunk 10]
```diff
@@ -62,6 +63,20 @@ class Widget extends Object
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Base/Widget.php]: See above

File: src/Frontend/Core/Engine/Footer.php [hunk 11]
```diff
@@ -9,19 +9,36 @@
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Footer.php]: See above

File: src/Frontend/Core/Engine/Breadcrumb.php [hunk 12]
```diff
@@ -24,10 +24,27 @@ class Breadcrumb extends FrontendBaseObject
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Breadcrumb.php]: See above

File: src/Frontend/Core/Engine/Block/Widget.php [hunk 13]
```diff
@@ -64,6 +65,20 @@ class Widget extends FrontendBaseObject
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Block/Widget.php]: See above

File: src/Frontend/Core/Engine/Block/Extra.php [hunk 14]
```diff
@@ -79,6 +80,20 @@ class Extra extends FrontendBaseObject
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Block/Extra.php]: See above

File: src/Frontend/Core/Engine/Navigation.php [hunk 15]
```diff
@@ -35,10 +35,27 @@ class Navigation extends FrontendBaseObject
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Navigation.php]: See above

File: src/Frontend/Core/Engine/Page.php [hunk 16]
```diff
@@ -83,11 +84,27 @@ class Page extends FrontendBaseObject
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Page.php]: See above

File: src/Frontend/Core/Engine/Base/Widget.php [hunk 17]
```diff
@@ -62,6 +63,20 @@ class Widget extends Object
     public $templatePath;
 
     /**
+     * TwigTemplate instance
+     *
+     * @var TwigTemplate
+     */
+    protected $tpl;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Base/Widget.php]: Why not $templating, as the service is called templating

File: src/Frontend/Core/Header/Header.php [hunk 18]
```diff
@@ -81,13 +83,30 @@ class Header extends Object
...
+     * @var TwigTemplate
+     */
+    protected $tpl;
+
+    /**
+     * URL instance
+     *
+     * @var Url
+     */
+    protected $URL;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Header/Header.php]: See above

File: src/Frontend/Core/Engine/Block/ModuleExtra.php [hunk 19]
```diff
@@ -0,0 +1,37 @@
...
+     * We will build the class name, initialise the class and call the execute method.
+     */
+    public function execute():void;
+
+    /**
+     * Get the assigned template.
+     *
+     * @return TwigTemplate
+     */
+    public function getTemplate():TwigTemplate;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: space between the semicolon and TwigTemplate

File: src/Frontend/Core/Engine/Block/ModuleExtra.php [hunk 20]
```diff
@@ -0,0 +1,37 @@
...
+     * @param string $action|null The action to load.
+     * @param mixed $data The data that was passed from the database.
+     */
+    public function __construct(KernelInterface $kernel, string $module, string $action = null, $data = null);
+
+    /**
+     * Execute the extra
+     * We will build the class name, initialise the class and call the execute method.
+     */
+    public function execute():void;
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: space between the semicolon and void

File: src/Frontend/Core/Engine/Block/ModuleExtra.php [hunk 21]
```diff
@@ -0,0 +1,37 @@
+<?php
+
+namespace Frontend\Core\Engine\Block;
+
+use Frontend\Core\Engine\TwigTemplate;
+use Symfony\Component\HttpKernel\KernelInterface;
+
+interface ModuleExtra
```
Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: Isn't it best practice to suffice interfaces with `Interface`, so `ModuleExtra` would become `ModuleExtraInterface`

File: UPGRADE_5.0.md (hunk 1 above)
Comment (carakas) [inline UPGRADE_5.0.md]: It is in the table below, but I've added a clarification for that below
c84fa7f50

File: UPGRADE_5.0.md (hunk 2 above)
Comment (carakas) [inline UPGRADE_5.0.md]: It is in the table below, but I've added a clarification for that below
50cb94814

File: src/Backend/Core/Engine/Base/Config.php (hunk 4 above)
Comment (carakas) [inline src/Backend/Core/Engine/Base/Config.php]: e25c63303

File: src/Backend/Core/Engine/Base/Config.php (hunk 6 above)
Comment (carakas) [inline src/Backend/Core/Engine/Base/Config.php]: e25c63303

File: src/Backend/Core/Engine/Base/Config.php (hunk 5 above)
Comment (carakas) [inline src/Backend/Core/Engine/Base/Config.php]: I would keep it in since it is used by some public methods like `isActionAvailableForActionType` and `getActionClass`

File: src/Backend/Core/Engine/Base/Action.php (hunk 8 above)
Comment (carakas) [inline src/Backend/Core/Engine/Base/Action.php]: 50cb948

File: src/Frontend/Core/Engine/Block/ModuleExtra.php (hunk 21 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: No, see http://verraes.net/2013/09/sensible-interfaces/

Comment (tijsverkoyen) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: Meuh, I'm not that big a fan of this, I'm more in favor of following Symfony. 
@forkcms/core-contributors what do you think?

File: src/Backend/Core/Engine/Base/Config.php (hunk 3 above)
Comment (carakas) [inline src/Backend/Core/Engine/Base/Config.php]: fixed it in e25c633
This was the result ob moving this code into its own method and I had forgotten to update the comments

File: src/Frontend/Core/Engine/Block/ModuleExtra.php (hunk 21 above)
Comment (matthiasmullie) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: http://www.php-fig.org/bylaws/psr-naming-conventions/

Comment (carakas) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: changed in #c5d28df5a

File: src/Frontend/Core/Engine/Block/ModuleExtra.php (hunk 20 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: 8ee1809ab

File: src/Frontend/Core/Engine/Block/ModuleExtra.php (hunk 19 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: 8ee1809ab

File: src/Frontend/Core/Engine/Block/ModuleExtra.php (hunk 20 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Block/ModuleExtra.php]: 8ee1809ab

File: UPGRADE_5.0.md (hunk 7 above)
Comment (carakas) [inline UPGRADE_5.0.md]: I kept them in because they are used rather often

File: src/Frontend/Core/Engine/Base/Block.php (hunk 9 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Base/Block.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Base/Widget.php (hunk 10 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Base/Widget.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Footer.php (hunk 11 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Footer.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Breadcrumb.php (hunk 12 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Breadcrumb.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Block/Widget.php (hunk 13 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Block/Widget.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Block/Extra.php (hunk 14 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Block/Extra.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Navigation.php (hunk 15 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Navigation.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Page.php (hunk 16 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Page.php]: fixed in c3052033b

File: src/Frontend/Core/Header/Header.php (hunk 18 above)
Comment (carakas) [inline src/Frontend/Core/Header/Header.php]: fixed in c3052033b

File: src/Frontend/Core/Engine/Base/Widget.php (hunk 17 above)
Comment (carakas) [inline src/Frontend/Core/Engine/Base/Widget.php]: fixed in 661804526

**Comment by carakas** [comment]
note to self: there is a problem with the user settings after installing on this branch
